# 📊 Data Preprocessing and Feature Engineering - Theory

---

# 🔹 1. What is Data Analysis?

Data Analysis is the process of collecting, cleaning, transforming, and interpreting data to discover useful information and support decision-making.

## 🎯 Why Data Analysis is Important?

✅ Helps organizations make better decisions.

✅ Identifies hidden patterns and trends.

✅ Improves business performance.

✅ Reduces risks and uncertainties.

✅ Supports Machine Learning and Predictive Analytics.

---

## 📌 Types of Data Analysis

### 1️⃣ Descriptive Analysis
Describes what happened in the past.

**Example:**
- Total Sales Last Month
- Number of Churned Customers

### 2️⃣ Diagnostic Analysis
Explains why something happened.

**Example:**
- Why customer churn increased.

### 3️⃣ Predictive Analysis
Predicts future outcomes.

**Example:**
- Predict whether a customer will churn.

### 4️⃣ Prescriptive Analysis
Suggests actions to improve outcomes.

**Example:**
- Recommend retention strategies.

---

# 🔹 2. Data Science Project Lifecycle

A Data Science Project follows a structured process from understanding the problem to deploying the solution.

## 📍 Step 1: Business Understanding

Understand the business problem and project objectives.

**Example:**
Predict customer churn.

---

## 📍 Step 2: Data Collection

Collect data from various sources.

### Data Sources

📄 CSV Files

📑 JSON Files

🗄️ SQL Databases

🌐 APIs

---

## 📍 Step 3: Data Cleaning

Improve data quality.

### Common Tasks

✅ Handle Missing Values

✅ Remove Duplicate Records

✅ Correct Data Types

✅ Handle Outliers

---

## 📍 Step 4: Exploratory Data Analysis (EDA)

Analyze data to understand patterns and relationships.

### Types of EDA

📊 Univariate Analysis

📈 Bivariate Analysis

📉 Multivariate Analysis

---

## 📍 Step 5: Feature Engineering

Create new features from existing data.

### Example

```python
Spend_per_Tenure = Total_Spend / Tenure
```

Feature Engineering improves model performance.

---

## 📍 Step 6: Model Building

Train Machine Learning algorithms.

### Common Models

🤖 Logistic Regression

🌳 Decision Tree

🌲 Random Forest

⚡ XGBoost

---

## 📍 Step 7: Model Evaluation

Evaluate model performance.

### Evaluation Metrics

🎯 Accuracy

🎯 Precision

🎯 Recall

🎯 F1 Score

---

## 📍 Step 8: Deployment

Deploy the trained model for real-world use.

### Examples

🌐 Web Application

📱 Mobile Application

☁️ Cloud Deployment

---

# 🔹 3. Machine Learning Problem Statement

## 🎯 Problem Statement

Customer churn is a major issue for subscription-based businesses.

The company wants to identify customers who are likely to leave the service.

---

## 🎯 Objective

Build a Machine Learning model that predicts customer churn using customer demographic and behavioral information.

---

## 📥 Input Features

👤 Age

🚻 Gender

📅 Tenure

📊 Usage Frequency

📞 Support Calls

💳 Payment Delay

⭐ Subscription Type

📄 Contract Length

💰 Total Spend

⏰ Last Interaction

---

## 🎯 Target Variable

### Churn

| Value | Meaning |
|---------|---------|
| 0 | Customer Retained |
| 1 | Customer Churned |

---

## ✅ Expected Outcome

The model should identify customers who are likely to churn so the company can take preventive actions and improve customer retention.

---

# 🔹 4. Tensors

A Tensor is a multi-dimensional data structure used in Machine Learning and Deep Learning.

Tensors are used to represent data in numerical form.

---

## 1️⃣ Scalar (0-D Tensor)

A single numerical value.

```python
import numpy as np

scalar = np.array(10)

print(scalar)
```

### Output

```python
10
```

---

## 2️⃣ Vector (1-D Tensor)

A collection of values.

```python
vector = np.array([10,20,30,40])

print(vector)
```

### Output

```python
[10 20 30 40]
```

---

## 3️⃣ Matrix (2-D Tensor)

A table consisting of rows and columns.

```python
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

print(matrix)
```

### Output

```python
[[1 2 3]
 [4 5 6]]
```

---

## 4️⃣ 3D Tensor

Multiple matrices combined together.

```python
tensor_3d = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(tensor_3d)
```

### Output

```python
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
```

---

## 📏 Tensor Dimensions

```python
print(scalar.ndim)
print(vector.ndim)
print(matrix.ndim)
print(tensor_3d.ndim)
```

### Output

```python
0
1
2
3
```

---

## 📐 Tensor Shapes

```python
print(vector.shape)
print(matrix.shape)
print(tensor_3d.shape)
```

### Output

```python
(4,)
(2,3)
(2,2,2)
```

---

# 🚀 Importance of Tensors

### 🤖 Machine Learning
Store training and testing data.

### 🧠 Deep Learning
Neural Networks operate on tensors.

### 🖼️ Computer Vision
Images are stored as tensors.

### 💬 Natural Language Processing (NLP)
Text embeddings are represented as tensors.

### 📊 Scientific Computing
Used in simulations and numerical calculations.

---

# ✅ Conclusion

Data Analysis helps transform raw data into meaningful insights.

The Data Science Lifecycle provides a structured approach to solving business problems.

Machine Learning models can predict customer churn using customer behavior data.

Tensors are the foundation of Machine Learning and Deep Learning because they efficiently represent multi-dimensional data.